---

extends: default

ignore: |
  node_modules/
  Makefile
  go.mod
  go.sum

rules:
  line-length:
    ignore: |
      /.github/workflows/*.yaml
      /.github/workflows/*.yml
      /.github/settings.yml
  truthy:
    ignore: |
      /.github/workflows/*.yaml
      /.github/workflows/*.yml
