#!/bin/bash

COVERAGE_FILE="coverage.out"
COVERAGE_THRESHOLD=80

go test -coverprofile="$COVERAGE_FILE" ./internal/...

coverage=$(go tool cover -func="$COVERAGE_FILE" | grep total | awk '{print $3}' | sed 's/%//')

if (( $(echo "$coverage < $COVERAGE_THRESHOLD" | bc -l) )); then
    rm "$COVERAGE_FILE"
    echo "Cannot push due to insufficient code coverage."
    echo "Current coverage: $COVERAGE_THRESHOLD% ($coverage%)"
    exit 1
fi

rm "$COVERAGE_FILE"
