---
name: 'Production CI: Sync labels'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    tags:
      - production
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
