---
name: "Development CI: Assign me"

on:
  pull_request:
    branches: ["develop"]

jobs:
  set_assignee:
    runs-on: ubuntu-latest
    tags:
      - development
    steps:
      - uses: actions/github-script@v7
        if: github.actor != 'dependabot[bot]'
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.actor],
            })
